name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua/install-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    # - name: show it
    #   run: find . | grep -v '.install'

    - uses: leafo/gh-actions-lua/install-luarocks@master

    - name: test lua
      run: lua -e 'print("hi from lua")'

    - name: test luarocks
      run: |
        echo $PATH
        env | grep LUA
        luarocks
        luarocks path
        luarocks install moonscript
        lua -e 'require("moon").p({1,2,3})'

