name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua/install-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-lua/install-luarocks@master

    - name: show it
      run: find .

    - name: test it
      run: lua -e 'print("hi from lua")'

    - name: test luarocks
      run: |
        .luarocks/bin/luarocks
        .luarocks/bin/luarocks path
        .luarocks/bin/luarocks install moonscript
