name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua/install-lua@master
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-lua/install-luarocks@master
      with:
        luaRocksVersion: "3.2.0"

    - name: show it
      run: find .

    - name: test it
      run: lua -e 'print("hi from lua")'
